apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: example@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: example@example.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: example@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: example@example.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token


#kubectl create secret generic cloudflare-api-token-secret --dry-run=client --from-literal=api-token=mysecretvalue -o yaml | \
#kubeseal \
#  --controller-name=sealed-secrets-controller \
#  --controller-namespace=default \
#  --format yaml > letsencrypt-secret.yaml
