apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
resources:
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: default
    files:
      - ../monitoring-config/control-plane.json
      - ../monitoring-config/cluster.json
      - ../monitoring-config/storage.json
    options:
      labels:
        grafana_dashboard: "1"

  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
