apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: true

      persistence:
        type: pvc
        enabled: true
        storageClassName: openebs-local-hostpath-conf
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        # annotations: {}
        finalizers:
          - kubernetes.io/pvc-protection
        # selectorLabels: {}
        subPath: "grafana"
        existingClaim: openebs-local-hostpath-conf-pvc

      ingress:
        ## If true, Grafana Ingress will be created
        ##
        enabled: true

        ## Annotations for Grafana Ingress
        ##
        annotations:
          # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          # kubernetes.io/ingress.class: public
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Frame-Options: allow";
          cert-manager.io/cluster-issuer: letsencrypt-production
          flame.pawelmalak/type: application
          flame.pawelmalak/name: Grafana
          flame.pawelmalak/url: https://example.com
          flame.pawelmalak/icon: https://user-images.githubusercontent.com/10999/43383564-afa9ea6c-93db-11e8-855b-de8be4f79756.png
        ## Labels to be added to the Ingress
        ##
        labels: {}

        ## Hostnames.
        ## Must be provided if Ingress is enable.
        ##
        # hosts:
        #   - grafana.domain.com
        hosts:
          - "example.com"

        ## Path for grafana ingress
        path: /

        ## TLS configuration for grafana Ingress
        ## Secret must be manually created in the namespace
        ##
        tls: []
        # - secretName: grafana-general-tls
        #   hosts:
        #   - grafana.example.com
