apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: true
      persistence:
        type: pvc
        enabled: true
        storageClassName: openebs-local-hostpath-conf
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        # annotations: {}
        finalizers:
          - kubernetes.io/pvc-protection
        # selectorLabels: {}
        subPath: "grafana"
        existingClaim: openebs-local-hostpath-conf-pvc
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Frame-Options: allow";
          cert-manager.io/cluster-issuer: letsencrypt-production
          flame.pawelmalak/type: application
          flame.pawelmalak/name: Grafana
          flame.pawelmalak/url: https://example.com
          flame.pawelmalak/icon: https://user-images.githubusercontent.com/10999/43383564-afa9ea6c-93db-11e8-855b-de8be4f79756.png
        labels: {}
        hosts:
          - "example.com"
        path: /
        pathType: Prefix
        ## TLS configuration for grafana Ingress
        ## Secret must be manually created in the namespace
        ##
        tls:
        - hosts:
          - "example.com"
          secretName: prometheus-tls
        # - secretName: grafana-general-tls
        #   hosts:
        #   - grafana.example.com

    prometheus:
      enabled: true
      prometheusSpec:
        storageSpec:
         volumeClaimTemplate:
           spec:
             storageClassName: openebs-local-hostpath-data
             accessModes: ["ReadWriteOnce"]
             resources:
               requests:
                 storage: 1Gi
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: public
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Frame-Options: allow";
          flame.pawelmalak/type: application
          flame.pawelmalak/name: Prometheus
          flame.pawelmalak/url: https://example.com
          flame.pawelmalak/icon: https://cdn.iconscout.com/icon/free/png-256/prometheus-282488.png
        labels: {}
        hosts:
          - "example.com"
        path: /
        pathType: Prefix
        ## TLS configuration for Prometheus Ingress
        ## Secret must be manually created in the namespace
        ##
        tls: []
          # - secretName: prometheus-general-tls
          #   hosts:
          #     - prometheus.example.com
